### ISSUE TITLE
Question about sampling phase

### ISSUE THREAD

**Issue by RAgNarokBear** [kopper-xdu/Adv-Diffusion#1]
I have a question about the sampling equation provided in the paper.
![image](https://github.com/kopper-xdu/Adv-Diffusion/assets/83484436/9f949faa-a11e-46ee-9a22-f9e6b20d90d3)
Is the variance Σ related to the parameter θ ? It seems that it is a equation w.r.t. DDPM sampler while you use a DDIM sampler in your code.
I can only found this sampling equation in LDM, and it looks different with yours.
![image](https://github.com/kopper-xdu/Adv-Diffusion/assets/83484436/0a0eb642-19e6-4cec-80d7-3407edb0a5ef)

**Comment by kopperx** [comment]
It depends on specific implementation, sigma theta do not affect the sampling result. In our code,.sigma theta do not depends on theta, it is fixed. you also can use a learned sigma.

**Comment by RAgNarokBear** [comment]
And I wonder why the approximate z_0 is calculated by alpha_t
![image](https://github.com/kopper-xdu/Adv-Diffusion/assets/83484436/3de63fb1-2da7-4541-a1d5-a4acbb38e2d4)
rather than alpha_(t-1) in DDPM:
![image](https://github.com/kopper-xdu/Adv-Diffusion/assets/83484436/707ccf27-061e-4dbf-aa7e-35ead1890f1b)

**Comment by kopperx** [comment]
This may be a mistake during paper writing. it should be alpha_(t-1).

**Comment by RAgNarokBear** [comment]
Thank you for your reply.
