### ISSUE TITLE
RuntimeError: The shape of the 2D attn_mask is torch.size([77, 77]), but should be (2, 2).

### ISSUE THREAD

**Issue by qiuyuzhao** [kopper-xdu/Adv-Diffusion#11]
Hello, may I ask what is the reason for this
![1723161737542](https://github.com/user-attachments/assets/1c600ebf-8ee0-4492-a324-3cadd88455a4)

**Comment by hwd-code** [comment]
I also have this question,do you solve it

**Comment by qiuyuzhao** [comment]
I remember it seems to be the environment version

**Comment by hwd-code** [comment]
you mean this is a version problem?
