### ISSUE TITLE
Could you provide the selected (attacker, victim) image pairs in the experiments of the paper?

### ISSUE THREAD

**Issue by yuuma002** [kopper-xdu/Adv-Diffusion#2]
Thanks for open-sourcing the wonderful work. We would like to build our own work based on it.

The paper writes:
```
In the evaluation stage, we randomly select 1000 images with different identities as the source images for both datasets. In particular, we also select 5 additional images as target images for each dataset, and randomly divide the 1000 source images into 5 groups, each corresponding to a different target image.
```
Could you provide the selected (attacker, victim) image pairs in the experiments of the paper?

Thanks a lot.

**Comment by kopperx** [comment]
You need to sample it from the corresponding dataset yourselves. It is easy to implement.
