### ISSUE TITLE
1

### ISSUE THREAD

**Issue by xudashui** [kopper-xdu/Adv-Diffusion#6]
why can only ffhq_sample src in the picture store 5,the code can run ,can explain it please?

**Comment by kopperx** [comment]
Please describe in detail the problem you are experiencing, I don't understand your question.

**Comment by xudashui** [comment]
when I put the number of picture in ffhq_sample/src more than 5，it occurs:

when fewer than 5:





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kopper-xdu/Adv-Diffusion"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月25日(星期一) 晚上6:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kopper-xdu/Adv-Diffusion] 1 (Issue #6)





 
Please describe in detail the problem you are experiencing, I don't understand your question.

**Comment by kopperx** [comment]
please carefully read the args and source code in eval.py.
