### ISSUE TITLE
list index of range

### ISSUE THREAD

**Issue by xuyuhui234** [kopper-xdu/Adv-Diffusion#7]
Hey,when I put 1000 pictures in celeba-hq/src,it seems that the DDIM sample just executed 5 pictures,then it shows:
LatentInpaintDiffusion: Running in eps-prediction mode
DiffusionWrapper has 865.93 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Data shape for DDIM sampling is (1, 4, 64, 64), eta 1.0
Running DDIM Sampling with 46 timesteps
DDIM Sampler: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 46/46 [00:25<00:00,  1.79it/s]
0 1
tensor([0.6384], device='cuda:0')
Data shape for DDIM sampling is (1, 4, 64, 64), eta 1.0
Running DDIM Sampling with 46 timesteps
DDIM Sampler: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 46/46 [00:25<00:00,  1.83it/s]
1 1
tensor([0.5925], device='cuda:0')
Data shape for DDIM sampling is (1, 4, 64, 64), eta 1.0
Running DDIM Sampling with 46 timesteps
DDIM Sampler: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 46/46 [00:25<00:00,  1.80it/s]
2 1
tensor([0.5624], device='cuda:0')
Data shape for DDIM sampling is (1, 4, 64, 64), eta 1.0
Running DDIM Sampling with 46 timesteps
DDIM Sampler: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 46/46 [00:25<00:00,  1.81it/s]
3 1
tensor([0.7904], device='cuda:0')
Data shape for DDIM sampling is (1, 4, 64, 64), eta 1.0
Running DDIM Sampling with 46 timesteps
DDIM Sampler: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 46/46 [00:25<00:00,  1.82it/s]
4 1
tensor([0.4227], device='cuda:0')
FaceNet  attack success(far@0.1) rate:  1.0
FaceNet  attack success(far@0.01) rate:  1.0
FaceNet  attack success(far@0.001) rate:  0.6
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00,  8.08it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:16<00:00, 59.93it/s]
FID:  183.48892773302015
  0%|▊                                                                                                                                                                | 5/1000 [00:02<09:02,  1.83it/s]
Traceback (most recent call last):
  File "/home/xulei/pan1/xyh/diff/Adv/psnr_ssim.py", line 24, in <module>
    true_img_name = true_img_names[i]
IndexError: list index out of range
can you please tell how to sovle it

**Comment by kopperx** [comment]
change the --num 5 to 1000
the --num option value need to be set less than or equal to your src images numbers.
example：python eval.py --model IR152 --dataset celeba --t 999 --save res --num 1000

**Comment by xuyuhui234** [comment]
thank you for your good job!
