### ISSUE TITLE
How is that represented

### ISSUE THREAD

**Issue by tanlingp** [kopper-xdu/Adv-Diffusion#8]
Please ask in the paper, "Specifically, we also select 5 additional images as target images for each dataset and randomly divide the 1000 source images into 5 groups, each group corresponding to a different target image." How is that represented

**Comment by kopperx** [comment]
每组200张图像对于一个target图像，一共五组。

**Comment by tanlingp** [comment]
请问您在代码中是如何体现的？

**Comment by kopperx** [comment]
需要你自己编写该部分代码
