### ISSUE TITLE
python psnr_ssim.py --dir1 res/img --dir2 celeba-hq_sample/src

### ISSUE THREAD

**Issue by hwd-code** [kopper-xdu/Adv-Diffusion#9]
usage: psnr_ssim.py [-h] [--dir0 DIR0] [--dir1 DIR1]
psnr_ssim.py: error: unrecognized arguments: --dir2 celeba-hq_sample/src
there is a error.

**Comment by kopperx** [comment]
Thank you. I will fix it.
